version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - db
    volumes:
      - db-data:/data/db

  apprise:
    image: bkonicek/apprise-api:latest
    container_name: apprise
    ports:
      - "8000:8000"
    networks:
      - apprise
    volumes:
      - apprise-data:/config

  check:
    build: app
    container_name: price_check
    depends_on:
      - apprise
      - mongodb
    networks:
      - db
      - apprise
    environment:
      ITEM_CATEGORIES: "CPU,GPU,Motherboard"
      ITEM_RANGES: "A2:B,C2:D,E2:F"
      DB_HOST: "mongodb:27017"
      CHECK_INTERVAL: "60"
      SHEET_ID: ${SHEET_ID}
      SHEETS_API_KEY: ${SHEETS_API_KEY}
      APPRISE_CONFIG_URL: http://apprise:8000/get/apprise

networks:
  db:
  apprise:

volumes:
  db-data:
  apprise-data:
